{
 "title": "System",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sys_uptime", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_cpu{type=\"sys\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"usr\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"nice\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"gnice\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"iowait\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"irq\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"soft\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"steal\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"guest\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_cpu{type=\"idle\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sys_load", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"MemTotal\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_mem{type=\"MemUsed\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"SwapTotal\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_mem{type=\"SwapUsed\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "FS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "sys_fs{type=\"total\"}",
     "legendFormat": "total"
    },
    {
     "expr": "sys_fs{type=\"used\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sys_mem{type=\"Apps\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"PageTables\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"SwapCached\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Slab\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Cached\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"Buffers\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"MemFree\"}",
     "legendFormat": "Unused"
    },
    {
     "expr": "sys_mem{type=\"SwapUsed\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sys_mem{type=\"HardwareCorrupted\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network Traffic Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "increase(sys_network[60m])", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Procs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"count\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"cpu\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sys_procs{name=\"mem\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Systemd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Unit States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sys_systemd_count", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sys_systemd_failed", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Open",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sys_ports", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "Apt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sys_apt", "legendFormat": "count" }
   ]
  },
  {
   "title": "Installed Packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sys_pkg", "legendFormat": "count" }
   ]
  },
  { "title": "Wireguard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Traffic Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "increase(sys_wg[60m])", "legendFormat": "{{type}}" }
   ]
  },
  { "title": "F2B", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Bans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_f2b{name=\"totalBanned\"}",
     "legendFormat": "{{type}} | {{name}}"
    },
    {
     "expr": "sys_f2b{name=\"currentlyBanned\"}",
     "legendFormat": "{{type}} | {{name}}"
    }
   ]
  },
  {
   "title": "Fails",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sys_f2b{name=\"totalFailed\"}",
     "legendFormat": "{{type}} | {{name}}"
    },
    {
     "expr": "sys_f2b{name=\"currentlyFailed\"}",
     "legendFormat": "{{type}} | {{name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Certs Valid Days",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sys_certbot", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "UFW Rules",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    { "expr": "sys_ufw", "legendFormat": "__auto" }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Processes Start",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 101 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples Scrape Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(scrape_series_added[60m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "{{code}} | {{handler}}" }
   ]
  },
  {
   "title": "Time Series Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(prometheus_tsdb_head_series_created_total[60m])",
     "legendFormat": "created"
    },
    {
     "expr": "increase(prometheus_tsdb_head_series_removed_total[60m])",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "count" }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "prometheus_tsdb_head_chunks", "legendFormat": "count" }
   ]
  }
 ]
}