{
 "title": "NodeJS",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NodeJS Version",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    { "expr": "nodejs_version_info", "legendFormat": "__auto" }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(irate(process_cpu_user_seconds_total[2m]) + irate(process_cpu_system_seconds_total[2m])) * 100",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{app!=\"\"}[1d])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes + nodejs_external_memory_bytes",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Active Handlers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Heap Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_total_bytes) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Heap Available",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_available_bytes) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (nodejs_heap_space_size_used_bytes) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}